Version 0.1
Dhii/storage-interface pull request #2
Opened 2017-01-23 18:37 UTC by XedinUnknown

Initial release.

2017-01-23 19:31 UTC, mecha requested changes
The `LICENSE` year needs to be updated to `2016-2017`.

Also, `codeclimate/php-test-reporter` is not required as a developer dependency.

2017-01-24 09:50 UTC, XedinUnknown commented
@mecha, requested changes made.

2017-01-24 10:06 UTC, mecha approved these changes

2017-01-24 10:26 UTC, mecha reviewed
LGTM

2017-01-24 10:57 UTC, merged